image: node:20

pipelines:
  default:
    - step:
        name: Install, Lint, and Build
        caches:
          - node
        script:
          - npm ci
          - npm run lint
          - npm run build
  pull-requests:
    '**':
      - step:
          name: PR Check (Install, Lint, Build)
          caches:
            - node
          script:
            - npm ci
            - npm run lint
            - npm run build 